version: "3.9"

services:
  # Frontend con Nginx
  frontend:
    image: nginx:latest
    container_name: app-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro      # tu c√≥digo frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # certificados en la EC2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
